name: my_cst2335_labs
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  floor: ^1.4.0
  sqflite: ^2.0.0


dev_dependencies:
  floor_generator: ^1.4.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/beef.jpg
    - images/chicken.jpg
    - images/pork.jpg
    - images/seafood.jpg
    - images/main_dishes.jpg
    - images/salad.jpg
    - images/side_dishes.jpg
    - images/crockpot.jpg
    - images/ice_cream.jpg
    - images/brownies.jpg
    - images/pies.jpg
    - images/cookies.jpg
